spring.datasource.url=jdbc:postgresql://dpg-d5i1jtl6ubrc738b5jvg-a:5432/wedding_database_efl6
spring.datasource.username=wedding_database_efl6_user
spring.datasource.password=hZ8onIY7TPgoVvLH80KuHqwOPqNrN7Ca
spring.datasource.driver-class-name=org.postgresql.Driver
